apiVersion: v1
kind: Namespace
metadata: 
  name: homolog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-homolog
  labels:
    app: front-end-homolog
spec:
  selector:
    matchLabels:
      app: front-end-homolog
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: front-end-homolog
    spec:
      containers:
        - name: nginx
          image: denirow/prog-redes
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-cip-homolog
spec:
  type: ClusterIP
  selector:
    app: front-end-homolog
  ports:
  - port: 80
    targetPort: 80

